# Conexión a MySQL en la nube (Aiven)
spring.datasource.url=jdbc:mysql://ejercicio-9-citlalyromanu-da4.b.aivencloud.com:18956/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
# AQUÍ PEGA TU CONTRASEÑA REAL (la que sale al darle al ojo en Aiven)
spring.datasource.password=AVNS_ZuBNrnAEiKe3LDEP5__

# Configuración de Driver y Hibernate
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

